class UserNotFoundException(BaseException):
    pass


class UserAlreadyExistsException(BaseException):
    pass
